import axios from 'axios';
import { auth } from '@/lib/firebase';

// API base URL - use environment variable or default to localhost
// Always append /api to the base URL for API routes
const API_BASE_URL = `${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/api`;

// Create axios instance
const api = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Request interceptor to add a fresh Firebase auth token. Firebase ID tokens expire
// after ~1 hour; getIdToken() returns the cached token when it's still valid and
// transparently refreshes it when it's not, so calling it per-request is cheap and
// keeps every API call authenticated for as long as the user stays signed in.
// Falls back to the last-known token in localStorage for the brief window before
// Firebase's auth state has hydrated.
api.interceptors.request.use(
  async (config) => {
    let token: string | null = null;

    if (auth.currentUser) {
      try {
        token = await auth.currentUser.getIdToken();
      } catch {
        token = localStorage.getItem('flourish_token');
      }
    } else {
      token = localStorage.getItem('flourish_token');
    }

    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
      localStorage.setItem('flourish_token', token);
    }
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

// Response interceptor for error handling
api.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      // Token expired or invalid
      localStorage.removeItem('flourish_token');
      localStorage.removeItem('flourish_user');
      window.location.href = '/auth';
    }
    return Promise.reject(error);
  }
);

// ---- PROFILE / ONBOARDING ----
export async function getProfile() {
  const { data } = await api.get('/auth/profile');
  return data;
}

export async function createProfile(payload: {
  email: string;
  display_name?: string;
  photo_url?: string;
  full_name: string;
  phone_number: string;
}) {
  const { data } = await api.post('/auth/profile', payload);
  return data;
}

export async function updateProfile(payload: Partial<{
  full_name: string;
  phone_number: string;
  display_name: string;
  photo_url: string;
  bio: string;
}>) {
  const { data } = await api.patch('/auth/profile', payload);
  return data;
}

export async function updatePrivacy(payload: Partial<{
  public_profile_enabled: boolean;
  show_email: boolean;
  show_phone: boolean;
}>) {
  const { data } = await api.patch('/auth/profile/privacy', payload);
  return data;
}

export async function updateNotificationPreferences(payload: Partial<{
  email_task_reminders: boolean;
  email_achievements: boolean;
  email_streak_risk: boolean;
  email_recommendations: boolean;
}>) {
  const { data } = await api.patch('/auth/profile/notification-preferences', payload);
  return data;
}

// ---- PLANTS ----
export async function getPlants() {
  const { data } = await api.get('/plants');
  return data.plants;
}

export async function createAutonomousPlant(plantName: string, userLocation?: string) {
  const { data } = await api.post('/plants/autonomous', { plant_name: plantName, user_location: userLocation });
  return data;
}

export async function createPlant(plant: any) {
  const { data } = await api.post('/plants', plant);
  return data;
}

export async function submitHealthCheck(plantId: string, healthCheck: any) {
  const { data } = await api.post(`/plants/${plantId}/health-check`, healthCheck);
  return data;
}

export async function getPlantSchedule(plantId: string) {
  const { data } = await api.get(`/plants/${plantId}/schedule`);
  return data;
}

export async function completeCareTask(plantId: string, scheduleId: string, notes?: string) {
  const { data } = await api.post(`/plants/${plantId}/schedule/complete`, { schedule_id: scheduleId, notes });
  return data;
}

// Calendar endpoints don't exist - use tasks/today instead
// export async function getTodaySchedule() {
//   const { data } = await api.get('/tasks/today');
//   return data;
// }

// ---- DASHBOARD ----
export async function getDashboardData() {
  const { data } = await api.get('/dashboard');
  return data;
}

// ---- TASKS ----
export async function getTodayTasks() {
  const { data } = await api.get('/tasks/today');
  return data.tasks;
}

// All pending (not-yet-completed) tasks across every plant, for the Calendar - watering/
// fertilizing occurrences generated by PlantService.create_projected_schedule span
// weeks/months ahead, not just today.
export async function getAllUpcomingTasks() {
  const { data } = await api.get('/tasks/?completed=false');
  return data;
}

export async function completeTask(taskId: string, notes?: string) {
  const { data } = await api.post(`/tasks/${taskId}/complete`, { notes });
  return data;
}

export async function snoozeTask(taskId: string, hours: number = 24) {
  const { data } = await api.post(`/tasks/${taskId}/snooze?hours=${hours}`);
  return data;
}

export async function rescheduleTask(taskId: string, dueDate: string) {
  const { data } = await api.patch(`/tasks/${taskId}/reschedule?due_date=${encodeURIComponent(dueDate)}`);
  return data;
}

// ---- AI CHAT ----
export async function chatWithAI(messages: any[]) {
  const { data } = await api.post('/chat', messages);
  return {
    response: data.response,
    suggestions: data.suggestions,
  };
}

export async function analyzeImage(imageData: string, plantId?: string) {
  const { data } = await api.post('/chat/analyze-image', imageData);
  return data;
}

// ---- IMAGES ----
export async function getPlantImage(plantName: string, species: string = '') {
  const { data } = await api.get(`/images/plant/${plantName}?species=${species}`);
  return data.image_url;
}

// Generate tasks for a plant
export async function generateTasksForPlant(plantId: string) {
  const { data } = await api.post(`/tasks/generate/${plantId}`);
  return data;
}

// ---- LEADERBOARD ----
export async function getLeaderboard(period: 'all_time' | 'monthly' | 'weekly' = 'all_time', limit: number = 100) {
  const { data } = await api.get(`/leaderboard/leaderboard?period=${period}&limit=${limit}`);
  return data;
}

export async function getUserStats() {
  const { data } = await api.get('/leaderboard/stats');
  return data;
}

export async function getMyLeaderboardEntry() {
  const { data } = await api.get('/leaderboard/leaderboard/me');
  return data;
}

// ---- NOTIFICATIONS ----
export async function getNotifications(unreadOnly: boolean = false, limit: number = 50) {
  const { data } = await api.get(`/notifications/?unread_only=${unreadOnly}&limit=${limit}`);
  return data.notifications;
}

export async function markNotificationRead(notificationId: string) {
  const { data } = await api.put(`/notifications/${notificationId}/read`);
  return data;
}

export async function markAllNotificationsRead() {
  const { data } = await api.put('/notifications/mark-all-read');
  return data;
}

export async function deleteNotification(notificationId: string) {
  const { data } = await api.delete(`/notifications/${notificationId}`);
  return data;
}

// ---- RECOMMENDATIONS ----
export async function getRecommendations() {
  const { data } = await api.get('/recommendations');
  return data;
}

export async function generateRecommendations(count: number = 3) {
  const { data } = await api.post(`/recommendations/generate?count=${count}`);
  return data;
}

export async function acceptRecommendation(recId: string) {
  const { data } = await api.post(`/recommendations/${recId}/accept`);
  return data;
}

export async function dismissRecommendation(recId: string) {
  const { data } = await api.post(`/recommendations/${recId}/dismiss`);
  return data;
}

// ---- AGENTIC PLANT LOOKUP ----
export async function lookupPlant(plantName: string) {
  const { data } = await api.post('/plants/lookup', { plant_name: plantName });
  return data;
}

// ---- MCP INTEGRATION ----
export async function getWeatherData(lat: number, lon: number) {
  const { data } = await api.get(`/mcp/weather/${lat}/${lon}`);
  return data;
}

export async function getPlantInfoMCP(plantName: string) {
  const { data } = await api.get(`/mcp/plant-info/${plantName}`);
  return data;
}

export default api;

// Get calendar events (placeholder implementation)
export async function getCalendarEvents() {
  // This would be implemented to get calendar-style events
  return [];
}

// Get care tasks (alias for getTodayTasks)
export async function getCareTasks() {
  return getTodayTasks();
}

// ---- STORAGE / FILE UPLOADS ----
export async function uploadPlantImage(plantId: string, file: File) {
  const formData = new FormData();
  formData.append('file', file);
  const { data } = await api.post(`/storage/upload/plant-image/${plantId}`, formData, {
    headers: { 'Content-Type': 'multipart/form-data' }
  });
  return data;
}

export async function uploadDocument(file: File) {
  const formData = new FormData();
  formData.append('file', file);
  const { data } = await api.post('/storage/upload/document', formData, {
    headers: { 'Content-Type': 'multipart/form-data' }
  });
  return data;
}

export async function uploadProfilePhoto(file: File) {
  const formData = new FormData();
  formData.append('file', file);
  const { data } = await api.post('/storage/upload/profile-photo', formData, {
    headers: { 'Content-Type': 'multipart/form-data' }
  });
  return data;
}

export async function deleteStorageFile(filePath: string) {
  const { data } = await api.delete(`/storage/delete/${encodeURIComponent(filePath)}`);
  return data;
}